
services:
  Image_server:
    image: python:3.12
    working_dir: /app
    ports:
      - 8383:8383
    command: >
      /bin/bash -c "pip install -q -r requirements.txt && python main.py"
    volumes:
      - .:/app
    restart: unless-stopped

